import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAppState, type ToolCategory, type ToolStatus } from "@/lib/app-state";
import { trpc } from "@/lib/trpc";

const categories: ToolCategory[] = ["Power tools", "Garden", "Hand tools", "Cleaning", "Outdoor"];
export default function AddToolScreen() {
  const { addTool, community } = useAppState();
  const createToolMutation = trpc.tools.create.useMutation();
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [category, setCategory] = useState<ToolCategory>("Power tools");
  const [status, setStatus] = useState<ToolStatus>("available");
  const submit = async () => { if (!name.trim() || !community) return; const tool = { name: name.trim(), description: description.trim() || "A useful tool to share with a neighbor.", category, status, icon: category === "Garden" ? "park" : category === "Cleaning" ? "cleaning-services" : category === "Outdoor" ? "stairs" : "construction", accent: "#D9E9DB" as const }; try { await createToolMutation.mutateAsync({ ...tool, communityId: community.id }); } catch { /* Keep the local draft usable if the network is temporarily unavailable. */ } addTool(tool); router.back(); };
  return <ScreenContainer className="px-5" containerClassName="bg-[#F6F1E8]"><ScrollView contentContainerStyle={{ paddingTop: 15, paddingBottom: 28 }}><View className="flex-row items-center mb-8"><Pressable onPress={() => router.back()} className="h-10 w-10 rounded-full bg-[#FFFCF7] items-center justify-center"><MaterialIcons name="close" size={22} color="#1F2924" /></Pressable><Text className="text-[25px] font-bold text-[#1F2924] ml-4">List a tool</Text></View><Text className="text-sm font-semibold text-[#6D7C73] mb-2">WHAT ARE YOU SHARING?</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Cordless drill" placeholderTextColor="#98A29C" className="h-14 rounded-2xl bg-[#FFFCF7] border border-[#E5DED1] px-4 text-[16px] text-[#1F2924] mb-6" /><Text className="text-sm font-semibold text-[#6D7C73] mb-3">CATEGORY</Text><View className="flex-row flex-wrap gap-2 mb-6">{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} className={`rounded-full px-4 py-3 border ${category === item ? "bg-[#2F6B4F] border-[#2F6B4F]" : "border-[#D8D0C2]"}`}><Text className={`text-[13px] font-semibold ${category === item ? "text-[#FFFCF7]" : "text-[#5C6A61]"}`}>{item}</Text></Pressable>)}</View><Text className="text-sm font-semibold text-[#6D7C73] mb-2">SHORT DESCRIPTION</Text><TextInput value={description} onChangeText={setDescription} multiline placeholder="What should a neighbor know?" placeholderTextColor="#98A29C" className="min-h-[112px] rounded-2xl bg-[#FFFCF7] border border-[#E5DED1] px-4 py-4 text-[16px] text-[#1F2924] mb-6" textAlignVertical="top" /><Text className="text-sm font-semibold text-[#6D7C73] mb-3">CURRENT STATUS</Text><View className="flex-row gap-3 mb-8">{(["available", "borrowed"] as ToolStatus[]).map((item) => <Pressable key={item} onPress={() => setStatus(item)} className={`flex-1 h-14 rounded-2xl items-center justify-center border ${status === item ? "bg-[#E3F1E7] border-[#3B8C64]" : "bg-[#FFFCF7] border-[#E5DED1]"}`}><Text className={`font-bold capitalize ${status === item ? "text-[#31714E]" : "text-[#6D7C73]"}`}>{item}</Text></Pressable>)}</View><Pressable onPress={submit} disabled={!name.trim()} style={({ pressed }) => [{ opacity: pressed ? 0.85 : name.trim() ? 1 : 0.5 }]} className="h-14 rounded-2xl bg-[#2F6B4F] items-center justify-center"><Text className="text-[#FFFCF7] font-bold text-[16px]">Post tool</Text></Pressable></ScrollView></ScreenContainer>;
}
