import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { communities, useAppState, type Community } from "@/lib/app-state";

export default function CommunityScreen() {
  const { selectCommunity, createCommunity, community } = useAppState();
  const [name, setName] = useState(""); const [description, setDescription] = useState("");
  const choose = (next: Community) => { selectCommunity(next); router.replace("/(tabs)"); };
  const create = () => { if (!name.trim()) { Alert.alert("Name your community", "Add a neighborhood or community name to continue."); return; } createCommunity(name, description || "A local community sharing useful things."); router.replace("/(tabs)"); };
  return <ScreenContainer className="px-5" containerClassName="bg-[#F6F1E8]"><ScrollView contentContainerStyle={{ flexGrow: 1, justifyContent: "center", paddingVertical: 28 }}><View className="mb-8"><View className="h-14 w-14 rounded-2xl bg-[#2F6B4F] items-center justify-center mb-5"><MaterialIcons name="handshake" size={30} color="#FFFCF7" /></View><Text className="text-[32px] leading-9 font-bold text-[#1F2924]">Set up your community</Text><Text className="text-[16px] leading-6 text-[#6D7C73] mt-3">Create the neighborhood or community you want to share with. You can change this later.</Text></View>{communities.length > 0 && <View className="mb-6">{communities.map((item) => <Pressable key={item.id} onPress={() => choose(item)} className="bg-[#FFFCF7] border border-[#E5DED1] rounded-2xl p-4 mb-3 flex-row items-center"><View className="h-12 w-12 rounded-xl bg-[#D9E9DB] items-center justify-center"><MaterialIcons name="location-city" size={24} color="#2F6B4F" /></View><View className="flex-1 ml-3"><Text className="text-[17px] font-bold text-[#1F2924]">{item.name}</Text><Text className="text-[13px] leading-5 text-[#6D7C73] mt-1">{item.description}</Text></View><MaterialIcons name={community?.id === item.id ? "check-circle" : "chevron-right"} size={24} color={community?.id === item.id ? "#2F6B4F" : "#9AA49D"} /></Pressable>)}</View>}<View className="bg-[#FFFCF7] border border-[#E5DED1] rounded-2xl p-4"><Text className="text-sm font-semibold text-[#6D7C73] mb-2">COMMUNITY NAME</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Cedar Street" placeholderTextColor="#98A29C" className="h-12 rounded-xl bg-[#F6F1E8] px-3 text-[#1F2924] mb-4" /><Text className="text-sm font-semibold text-[#6D7C73] mb-2">SHORT DESCRIPTION <Text className="font-normal">(optional)</Text></Text><TextInput value={description} onChangeText={setDescription} placeholder="What makes this community yours?" placeholderTextColor="#98A29C" multiline className="min-h-[76px] rounded-xl bg-[#F6F1E8] px-3 py-3 text-[#1F2924]" textAlignVertical="top" /><Pressable onPress={create} className="h-12 rounded-xl bg-[#2F6B4F] items-center justify-center mt-4"><Text className="font-bold text-[#FFFCF7]">Create community</Text></Pressable></View><Text className="text-[12px] leading-5 text-[#89948D] text-center mt-5">Your board, wishlist, requests, and profile will be organized around this community.</Text></ScrollView></ScreenContainer>;
}
