import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { FlatList, Pressable, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAppState } from "@/lib/app-state";

export default function ProfileScreen() {
  const { tools, toggleToolStatus } = useAppState();
  const mine = tools.filter((item) => item.isMine);
  return <ScreenContainer className="px-5" containerClassName="bg-[#F6F1E8]"><FlatList data={mine} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingTop: 24, paddingBottom: 32 }} ListHeaderComponent={<View><View className="flex-row items-center mb-7"><View className="h-16 w-16 rounded-full bg-[#2F6B4F] items-center justify-center"><Text className="text-[24px] font-bold text-[#FFFCF7]">Y</Text></View><View className="ml-4"><Text className="text-[27px] font-bold text-[#1F2924]">Your lending shelf</Text><Text className="text-[14px] text-[#6D7C73] mt-1">Maplewood · building trust locally</Text></View></View><View className="bg-[#E3F1E7] rounded-2xl p-4 mb-7 flex-row"><MaterialIcons name="volunteer-activism" size={24} color="#2F6B4F" /><Text className="flex-1 ml-3 text-[14px] leading-5 text-[#3A5D48]">Small acts of sharing make a neighborhood more useful. Keep your listings current so neighbors know what to count on.</Text></View><View className="flex-row items-center justify-between mb-3"><Text className="text-[21px] font-bold text-[#1F2924]">My tools</Text><Pressable onPress={() => router.push("/add-tool")} className="flex-row items-center"><MaterialIcons name="add" size={18} color="#2F6B4F" /><Text className="text-[14px] font-bold text-[#2F6B4F] ml-1">Add tool</Text></Pressable></View></View>} renderItem={({ item }) => <View className="bg-[#FFFCF7] border border-[#E5DED1] rounded-2xl p-4 mb-3 flex-row items-center"><View style={{ backgroundColor: item.accent }} className="h-14 w-14 rounded-xl items-center justify-center"><MaterialIcons name={item.icon as keyof typeof MaterialIcons.glyphMap} size={28} color="#2F6B4F" /></View><View className="flex-1 ml-3"><Text className="text-[16px] font-bold text-[#1F2924]">{item.name}</Text><Text className="text-[13px] text-[#6D7C73] mt-1">{item.status === "available" ? "Ready to lend" : "Marked as borrowed"}</Text></View><Pressable onPress={() => toggleToolStatus(item.id)} className={`rounded-full px-3 py-2 ${item.status === "available" ? "bg-[#E3F1E7]" : "bg-[#F5E9D2]"}`}><Text className={`text-[11px] font-bold ${item.status === "available" ? "text-[#31714E]" : "text-[#9A6617]"}`}>{item.status === "available" ? "AVAILABLE" : "BORROWED"}</Text></Pressable></View>} ListEmptyComponent={<View className="items-center py-12"><Text className="text-[#6D7C73]">You have not listed a tool yet.</Text></View>} /></ScreenContainer>;
}
