import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAppState } from "@/lib/app-state";

export default function RequestsScreen() {
  const { requests, community } = useAppState();
  const [segment, setSegment] = useState<"sent" | "received">("sent");
  const visible = requests.filter((item) => (item.communityId ?? community?.id) === community?.id).filter((item) => item.direction === segment);
  return <ScreenContainer className="px-5" containerClassName="bg-[#F6F1E8]"><FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingTop: 24, paddingBottom: 32, flexGrow: 1 }} ListHeaderComponent={<View><Text className="text-sm font-semibold text-[#6D7C73]">YOUR NEIGHBORHOOD</Text><Text className="text-[32px] font-bold text-[#1F2924] mt-1 mb-6">Requests</Text><View className="flex-row p-1 rounded-2xl bg-[#EDE5D8] mb-6"><Pressable onPress={() => setSegment("sent")} className={`flex-1 py-3 rounded-xl items-center ${segment === "sent" ? "bg-[#FFFCF7]" : ""}`}><Text className={`font-bold ${segment === "sent" ? "text-[#2F6B4F]" : "text-[#6D7C73]"}`}>Sent</Text></Pressable><Pressable onPress={() => setSegment("received")} className={`flex-1 py-3 rounded-xl items-center ${segment === "received" ? "bg-[#FFFCF7]" : ""}`}><Text className={`font-bold ${segment === "received" ? "text-[#2F6B4F]" : "text-[#6D7C73]"}`}>Received</Text></Pressable></View></View>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/request/[id]", params: { id: item.id } })} className="bg-[#FFFCF7] border border-[#E5DED1] rounded-2xl p-4 mb-3"><View className="flex-row items-center"><View className="h-11 w-11 rounded-full bg-[#D9E9DB] items-center justify-center"><MaterialIcons name={item.direction === "sent" ? "north-east" : "south-west"} size={22} color="#2F6B4F" /></View><View className="flex-1 ml-3"><Text className="text-[16px] font-bold text-[#1F2924]">{item.toolName}</Text><Text className="text-[13px] text-[#6D7C73] mt-1">{item.direction === "sent" ? "To owner" : `From ${item.neighbor}`}</Text></View><Text className="text-[12px] font-bold capitalize text-[#9A6617]">{item.status}</Text></View><Text numberOfLines={1} className="text-[14px] text-[#526159] mt-4">{item.preview}</Text></Pressable>} ListEmptyComponent={<View className="items-center justify-center flex-1"><MaterialIcons name="forum" size={44} color="#9AA49D" /><Text className="text-lg font-bold text-[#1F2924] mt-4">No {segment} requests</Text><Text className="text-sm text-[#6D7C73] mt-1 text-center">When a conversation starts, it will show up here.</Text></View>} /></ScreenContainer>;
}
